namespace backend.Mappings {
    public static class AmbiguousMappingProvider {
        public static IReadOnlyDictionary<string, string[]> AmbiguousMapping { get; } = new Dictionary<string, string[]>(StringComparer.OrdinalIgnoreCase) {
            { "Brand",      new[] { "UTILITY", "MIDDLE", "BOTTOM" } },
            { "Lux",        new[] { "UTILITY", "MIDDLE" } },
            { "Mel",        new[] { "MIDDLE", "BOTTOM", "UTILITY" } },
            { "Neeko",      new[] { "UTILITY", "MIDDLE" } },
            { "Pantheon",   new[] { "UTILITY", "TOP", "MIDDLE" } },
            { "Poppy",      new[] { "UTILITY", "TOP" } },
            { "Morgana",    new[] { "UTILITY", "MIDDLE" } },
            { "Senna",      new[] { "UTILITY", "BOTTOM" } },
            { "Seraphine",  new[] { "UTILITY", "BOTTOM", "MIDDLE" } },
            { "Swain",      new[] { "UTILITY", "MIDDLE", "BOTTOM", "TOP" } },
            { "TahmKench",  new[] { "UTILITY", "TOP" } },
            { "Velkoz",     new[] { "UTILITY", "MIDDLE" } },
            { "Nidalee",    new[] { "UTILITY", "TOP" } },
            { "Maokai",     new[] { "UTILITY", "TOP" } },
            { "Xerath",     new[] { "UTILITY", "MIDDLE" } },
            { "Corki",      new[] { "BOTTOM", "MIDDLE" } },
            { "Lucian",     new[] { "BOTTOM", "MIDDLE" } },
            { "Smolder",    new[] { "BOTTOM", "MIDDLE", "TOP" } },
            { "Tristana",   new[] { "BOTTOM", "MIDDLE" } },
            { "Vayne",      new[] { "BOTTOM", "TOP" } },
            { "Ziggs",      new[] { "BOTTOM", "MIDDLE" } },
            { "Zyra",       new[] { "UTILITY", "BOTTOM" } },
            { "Akali",      new[] { "MIDDLE", "TOP" } },
            { "Aurora",     new[] { "MIDDLE", "TOP" } },
            { "Kennen",     new[] { "MIDDLE", "TOP" } },
            { "Cassiopeia", new[] { "MIDDLE", "TOP" } },
            { "Chogath",    new[] { "TOP", "MIDDLE" } },
            { "Galio",      new[] { "MIDDLE", "UTILITY", "TOP" } },
            { "Hwei",       new[] { "MIDDLE", "BOTTOM", "UTILITY" } },
            { "Irelia",     new[] { "TOP", "MIDDLE" } },
            { "Ryze",       new[] { "MIDDLE", "TOP" } },
            { "Sylas",      new[] { "MIDDLE", "TOP" } },
            { "Veigar",     new[] { "MIDDLE", "BOTTOM", "UTILITY" } },
            { "Viktor",     new[] { "MIDDLE", "BOTTOM" } },
            { "Syndra",     new[] { "MIDDLE", "BOTTOM" } },
            { "Vladimir",   new[] { "MIDDLE", "TOP" } },
            { "Yasuo",      new[] { "MIDDLE", "TOP", "BOTTOM" } },
            { "Yone",       new[] { "MIDDLE", "TOP" } },
            { "Zoe",        new[] { "MIDDLE", "UTILITY" } },
            { "Taliyah",    new[] { "MIDDLE", "BOTTOM" } },
            { "Camille",    new[] { "TOP", "UTILITY" } },
            { "Heimer",     new[] { "TOP", "MIDDLE", "BOTTOM", "UTILITY" } },
            { "Jayce",      new[] { "TOP", "MIDDLE" } },
            { "Karma",      new[] { "UTILITY", "MIDDLE", "TOP" } },
        };
    }
}